version: '3'

services:
  harvest:
    image: szukalski/netapp-harvest
    volumes:
      - data:/opt/netapp-harvest
      - ./netapp-harvest.conf:/opt/netapp-harvest/netapp-harvest.conf
    links:
      - influxdb
      - grafana
    restart: always
    depends_on:
      - "influxdb"
  influxdb:
    image: influxdb:latest
    volumes:
      - data:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
      - "2003:2003"
    env_file:
      - 'env.influxdb'
    restart: always
  grafana:
    image: grafana/grafana:latest
    volumes:
      - data:/var/lib/grafana
    links:
      - influxdb
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    depends_on:
      - "influxdb"
    restart: always

volumes:
  data:
